Aria-Control-Add ->  Added the aria control attr to the date input
Availity/react-dates pull request #14
Opened 2022-07-27 18:09 UTC by mtramantT

2022-08-01 19:29 UTC, jordan-a-young requested changes
The `@availity/date` component uses [SingleDatePicker](https://github.com/Availity/availity-react/blob/master/packages/date/src/Date.js#L6) for the component. Would you be able to add a unit test for that component that checks the id and aria-control are set properly?

2022-08-01 19:29 UTC, jordan-a-young commented on src/components/DateInput.jsx
> +          aria-control={`${id}-dayPicker_popup`}
Let's keep it uniform and use kebab case throughout, `${id}-day-picker-popup`

2022-08-01 19:29 UTC, jordan-a-young commented on src/components/DayPickerSingleDateController.jsx
> +  id: PropTypes.string,
We should mark this as `required` since it will break 508 when it's not there

2022-08-01 19:29 UTC, jordan-a-young commented on src/components/DayPickerSingleDateController.jsx
> +  id: 'dayPicker_popup',
Since we are going to mark as required, then we can remove the default

2023-03-07 19:51 UTC, LauRoxx commented
resolved with https://github.com/Availity/react-dates/pull/15

2023-03-07 19:51 UTC, closed without merging